---
- name: Configure MariaDB on Fedora
  hosts: fedora
  become: yes

  vars:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"

  tasks:
    - name: Ensure MariaDB is installed
      dnf:
        name: "{{ db_package }}"
        state: present

    - name: Ensure MariaDB service is enabled and started
      service:
        name: "{{ db_service }}"
        state: started
        enabled: yes

    - name: Ensure firewall allows DB port
      firewalld:
        port: "{{ db_port }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      when: db_port is defined

    - name: Install MySQL Python bindings
      dnf:
        name: python3-PyMySQL
        state: present

