---
- name: Using Variables and Facts
  hosts: webservers
  become: yes

  vars:
    package_name: nginx
    service_name: nginx

  tasks:
    - name: Install a package
      dnf:
        name: "{{ package_name }}"
        state: present

    - name: Ensure the service is running
      systemd:
        name: "{{ service_name }}"
        state: started
        enabled: yes

    - name: Print OS information
      debug:
        msg: "The operating system is {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
