---
- name: Create secretuser with sudo privileges
  hosts: fedora
  vars_files:
    - /home/igor/book_ansible/secrets.yml

  tasks:
    - name: Ensure secretuser exists
      user:
        name: secretuser
        password: "{{ user_password | password_hash('sha512') }}"
        shell: /bin/bash
        home: /home/secretuser
        create_home: yes

    - name: Create sudoers file for secretuser
      copy:
        dest: /etc/sudoers.d/secretuser
        content: "secretuser ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'

